apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-pipeline-python
  labels:
    app: github-pipeline-python
spec:
  selector:
    matchLabels:
      app: github-pipeline-python
  template:
    metadata:
      labels:
        app: github-pipeline-python
    spec:
      serviceAccountName: azure-devops-admin
      imagePullSecrets:
        - name: docker-mm-nexus
      containers:
        - name: github-pipeline-python
          image: 482780835707.dkr.ecr.us-west-2.amazonaws.com/sys-94:${{ github.sha }} 
